# Madlibs is a game where you are prompted to enter words, and those words are then used to fill in the blanks of a story.

protagonist = input("Enter the name of the protagonist: ")
seller = input("Enter the name of a seller: ")
adj1 = input("Enter an adjective to describe the items: ")
noun1 = input("Enter a noun (person, place, or thing): ")
adj2 = input("Enter another adjective: ")
adj3 = input("Enter another adjective: ")
verb1 = input("Enter a verb ending with ing: ")
verb2 = input("Enter another verb ending with ing: ")
verb3 = input("Enter another verb ending with ing: ")

print(f"Today, {protagonist} is walking through the streets of a small village when he comes across a {seller} selling some {adj1} goods.")
print(f"{seller}: 'Hey there, {protagonist}! I've got some rare items for sale. Would you like to take a look?'")
print(f"{protagonist} decides to take a look at the {adj1} goods. He sees a {noun1} that catches his eye.")
print(f"{protagonist}: 'Wow, this {noun1} looks really {adj2}! How much is it?'")
print(f"{seller}: 'It's only 100 pesetas!'")            
print(f"{protagonist} decides to buy the {noun1} and continues walking through the village. He sees a {adj3} shop and decides to go inside.")
print(f"Inside the shop, {protagonist} sees a {adj3} item that he really wants. He asks the shopkeeper about it.")
print(f"{protagonist}: 'Excuse me, how much is that {adj3} item?'")
print(f"Shopkeeper: 'That {adj3} item is 200 pesetas.'")
print(f"{protagonist} decides to buy the {adj3} item and continues walking through the village. He sees a group of people {verb1} in the town square.")
print(f"{protagonist} decides to join in and starts {verb2} with them. After a while, he gets tired and decides to go home. On his way back, he sees a {adj3} item that he really wants.")
print(f"{protagonist} decides to buy the {adj3} item and continues walking through the village. He sees a group of people {verb3} in the town square.")
print(f"{protagonist} decides to join in and starts {verb3} with them. After a while, he gets tired and decides to go home to go play some bingo.")
